Set Shell zsh
Set TypingSpeed 75ms
Set FontSize 22
Set Width 1300
Set Height 650
Output demo.gif
Sleep 1s
Type "hello!"
Sleep 1s
Backspace 9
Type "this is my tasks!"
Sleep 500ms
Backspace 18
Sleep 1s
Type "./my-tasks"
Enter
Sleep 2s
Type "a"
Sleep 500ms
Type "Buy groceries"
Enter
Sleep 1s
Type "a"
Sleep 500ms
Type "Read a book"
Enter
Sleep 1.5s
Type " "
Sleep 1s
Down
Down
Type "d"
Sleep 1s
Type "/"
Type "buy"
Sleep 1.5s
Escape
Sleep 5s
